{% set name = "numbalsoda" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/numblsoda/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 05b52d576850f900d83098fe70cb28b57d00089132095672788818fa95fcdac7

build:
  number: 0
  # script: "CMAKE_GENERATOR=\"NMake Makefiles\" {{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - cmake
  host:
    - python
    - pip
    - setuptools
    - wheel
    - scikit-build
    - ninja
  run:
    - python
    - numpy
    - numba
    
test:
  imports:
    - numbalsoda

about:
  home: https://github.com/Nicholaswogan/numbalsoda
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python wrapper of LSODA (solving ODEs) which can be called from within numba functions.'

extra:
  recipe-maintainers:
    - Tobias-fischer
    - Nicholaswogan
